from django.conf.urls import include, url
from . import views

urlpatterns = (
    url(r'^$',views.index,name="macs_home"),
    url(r'^q/(\d+)/$',views.json_download_members),
    url(r'^q/(\d+)/([a-fA-F0-9]{2,})/$',views.json_validate_member),
    url(r'^q/schedule/$',views.json_get_schedule),
    url(r'^q/schedule/(\d{2,4})/(\d{1,2})/(\d{1,2})/$',views.json_get_schedule),
    url(r'^q/status/(\d+)/$',views.json_resource_status),
    url(r'^members/create/$',views.member_create,name="member_create"),
    url(r'^members/$',views.member_list,name="members"),
    url(r'^members/(\d+)/$',views.member_view,name="member_view"),
    url(r'^members/(\d+)/edit/$',views.member_edit,name="member_edit"),
    url(r'^members/(\d+)/add_resource/$',views.add_resource_access,name="member_add_resource"),
    url(r'^members/(\d+)/remove_resource/(\d+)/$',views.remove_resource_access,name="member_remove_resource"),
    url(r'^members/(\d+)/manage_keycards/$',views.member_manage_keycards,name="member_keycards"),
    url(r'^resources/create/$',views.resource_create,name="resource_create"),
    url(r'^resources/(\d+)/$',views.resource_view,name="resource_view"),
    url(r'^resources/$',views.resource_list,name="resources"),
    url(r'^resources/(\d+)/edit/$',views.resource_edit,name="resource_edit"),
    url(r'^resources/(\d+)/lock/$',views.resource_lock,name="resource_lock"),
    url(r'^resources/(\d+)/unlock/$',views.resource_unlock,name="resource_unlock"),
    url(r'^keycards/$',views.keycard_manage_all,name="keycards"),
    url(r'^keycards/(\d+)/$',views.keycard_manage,name="keycard_manage"),
    url(r'^keycards/(\d+)/set_active/$',views.keycard_set_active,name="keycard_activate"),
    url(r'^keycards/(\d+)/set_inactive/$',views.keycard_set_inactive,name="keycard_deactivate"),
    url(r'^keycards/(\d+)/unassign/$',views.keycard_unassign,name="keycard_unassign"),
    url(r'^keycards/(\d+)/set_lockout/$',views.keycard_set_lockout_card,name="keycard_set_lockout"),
    url(r'^keycards/(\d+)/unset_lockout/$',views.keycard_unset_lockout_card,name="keycard_unset_lockout"),
    url(r'^keycards/upload/$',views.keycard_csv_upload,name="keycards_upload"),
    url(r'^keycards/create/$',views.keycard_batch_create,name="keycards_create"),
    url(r'^reports/access_log/$',views.report_access_log,name="report_access"),
    url(r'^reports/activity_log/$',views.report_activity_log,name="report_activity"),
    url(r'^schedule/$',views.schedule_show,name="schedule"),
    url(r'^schedule/daily/add/$',views.schedule_add_daily,name="schedule_daily_add"),
    url(r'^schedule/daily/(\d+)/edit/$',views.schedule_edit_daily,name="schedule_daily_edit"),
    url(r'^schedule/daily/(\d+)/delete/$',views.schedule_remove_daily,name="schedule_daily_delete"),
    url(r'^schedule/exc/add/$',views.schedule_add_exception,name="schedule_exception_add"),
    url(r'^schedule/exc/(\d+)/edit/$',views.schedule_edit_exception,name="schedule_exception_edit"),
    url(r'^schedule/exc/(\d+)/delete/$',views.schedule_remove_exception,name="schedule_exception_delete"),
    
)
